# Generated by Django 4.1.5 on 2023-02-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="image", new_name="images",),
    ]
